/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "settings.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SETTINGS_Settings, SETTINGS_Settings, AUTO)


PB_BIND(SETTINGS_Screen, SETTINGS_Screen, AUTO)


PB_BIND(SETTINGS_Beacon, SETTINGS_Beacon, AUTO)


PB_BIND(SETTINGS_LedRing, SETTINGS_LedRing, AUTO)



