repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-import-order]
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.4.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg]
